apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudcmr-back
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/truaro-test-gcp/cloudcmr-back:${IMAGE_VERSION}
        ports:
          - containerPort: 8080
        env:
        - name: DATASTORE_NAMESPACE
          value: ${DATASTORE_NAMESPACE}
        - name: MEMBER_SUBSCRIPTION_NAME
          value: ${MEMBER_SUBSCRIPTION_NAME}
        - name: JAVA_TOOL_OPTIONS
          value: "-agentpath:/opt/cdbg/cdbg_java_agent.so -agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=cloudcmr-back,-cprof_enable_heap_sampling=true"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
