server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
firebase:
  projectId: truaro-test-gcp

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics