server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
firebase:
  projectId: truaro-test-gcp

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

cors.configuration.allowOrigins: http://localhost:8088,https://staging-truaro-test-gcp.web.app,https://staging-truaro-test-gcp.firebaseapp.com,https://truaro-test-gcp.web.app,https://truaro-test-gcp.firebaseapp.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  cloud:
    gcp:
      datastore:
        namespace: ${DATASTORE_NAMESPACE:localtest}