server:
  port: ${PORT:8080}
  error:
    include-message: always
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 80
firebase:
  projectId: truaro-test-gcp

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring:
  cloud:
    gcp:
      datastore:
        namespace: ${DATASTORE_NAMESPACE:localtest}

subscription.name: ${MEMBER_SUBSCRIPTION_NAME:test-memberServiceSubscription}